# stub to call common GitHub Action (GA) as part of Continuous Integration (CI) Pull Request process checks for main branch
# inputs are described in the <org>/common-github-actions/<GA.yml> with same name as this stub
#
# secrets are inherited from the calling workflow, typically SONAR_TOKEN, SONAR_HOST_URL, GH_TOKEN, AKEYLESS_JWT_ID

name: CI Pull Request on Main Branch

on: 
  pull_request:
    branches: [ main, release/** ]
  push:
    branches: [ main, release/** ]

  workflow_dispatch:

env:
  STUB_VERSION: "1.0.0" 
  
jobs: 
  echo_inputs:
    name: 'Echo stub version'
    runs-on: ubuntu-latest
    steps:
      - name: echo version of stub and inputs
        run: |
          echo "[ci-main-pull-request-stub.yml] version $STUB_VERSION"

  call-ci-main-pr-check-pipeline:
    uses: chef/common-github-actions/.github/workflows/ci-main-pull-request.yml@main
    secrets: inherit
    with:   
      visibility: ${{ github.event.repository.visibility }} 
      
      perform-complexity-checks: true
      # scc-output-filename: 'scc-output.txt'
      perform-trufflehog-scan: true
      # perform-srcclr-scan: false
      # perform-veracode-sca-scan: false
      perform-blackduck-sca-scan: false
      
      build: true
      language: 'Ruby'  
      unit-tests: true

      # go-private-modules:
      
      perform-sonarqube-sca-scan: true
      perform-sonar-build: true
      # build-profile: 'default' 
      report-unit-test-coverage: true

      report-to-atlassian-dashboard: true
      quality-product-name: 'Chef360'
      # quality-sonar-app-name: 'YourSonarAppName'
      # quality-testing-type: 'Integration'
      # quality-service-name: 'YourServiceOrRepoName'
      # quality-junit-report: 

      # perform-blackduck-coverity: false
      perform-blackduck-polaris: false

      package-binaries: true
      habitat-build: true
      publish-packages: true

      generate-sbom: true
      export-github-sbom: true
      generate-blackduck-polaris-sbom: true
      generate-msft-sbom: true
      license_scout: true